# Generated by Django 5.0.4 on 2024-04-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='visits',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
