# Generated by Django 5.0.4 on 2024-04-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlshortener_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
